=== poskryakov/masterjava/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="Payload">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Project" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence >
                            <xs:element ref="City" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Project">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="description"/>
                <xs:element ref="Group" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Group">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="User" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
            <xs:attribute type="groupType" name="type" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="groupType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REGISTERING"/>
            <xs:enumeration value="CURRENT"/>
            <xs:enumeration value="FINISHED"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="User">
        <xs:complexType>
            <xs:attribute type="xs:string" name="fullName" use="required"/>
            <xs:attribute type="xs:string" name="email" use="required"/>
            <xs:attribute type="xs:IDREF" name="city" use="required"/>
            <xs:attribute type="flagType" name="flag" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ACTIVE"/>
            <xs:enumeration value="DELETED"/>
            <xs:enumeration value="SUPERUSER"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="City">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:ID" name="id" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== poskryakov/masterjava/src/main/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">
    <Project name="topjava">
        <description>Описание проекта Top Java.</description>
        <Group name="topjava01" type="FINISHED">
            <User fullName="Admin" email="admin@javaops.ru" city="spb" flag="SUPERUSER"/>
            <User fullName="User1 topjava01" email="user1t01@usermail.ru" city="kiv" flag="ACTIVE"/>
            <User fullName="User2 topjava01" email="user2t01@usermail.ru" city="mnsk" flag="DELETED"/>
        </Group>
        <Group name="topjava02" type="CURRENT">
            <User fullName="Admin" email="admin@javaops.ru" city="spb" flag="SUPERUSER"/>
            <User fullName="User1 topjava02" email="user1t02@usermail.ru" city="kiv" flag="ACTIVE"/>
            <User fullName="User2 topjava02" email="user2t02@usermail.ru" city="mnsk" flag="DELETED"/>
        </Group>
        <Group name="topjava03" type="REGISTERING">
            <User fullName="Admin" email="admin@javaops.ru" city="spb" flag="SUPERUSER"/>
            <User fullName="User1 topjava03" email="user1t03@usermail.ru" city="kiv" flag="ACTIVE"/>
            <User fullName="User2 topjava03" email="user2t03@usermail.ru" city="mnsk" flag="DELETED"/>
        </Group>
    </Project>
    <Project name="masterjava">
        <description>Описание проекта Master Java.</description>
        <Group name="masterjava01" type="FINISHED">
            <User fullName="Admin" email="admin@javaops.ru" city="spb" flag="SUPERUSER"/>
            <User fullName="User1 masterjava01" email="user1m01@usermail.ru" city="kiv" flag="ACTIVE"/>
            <User fullName="User2 masterjava01" email="user2m01@usermail.ru" city="mnsk" flag="DELETED"/>
        </Group>
        <Group name="masterjava02" type="CURRENT">
            <User fullName="Admin" email="admin@javaops.ru" city="spb" flag="SUPERUSER"/>
            <User fullName="User1 masterjava02" email="user1m02@usermail.ru" city="kiv" flag="ACTIVE"/>
            <User fullName="User2 masterjava02" email="user2m02@usermail.ru" city="mnsk" flag="DELETED"/>
        </Group>
        <Group name="masterjava03" type="REGISTERING">
            <User fullName="Admin" email="admin@javaops.ru" city="spb" flag="SUPERUSER"/>
            <User fullName="User1 masterjava03" email="user1m03@usermail.ru" city="kiv" flag="ACTIVE"/>
            <User fullName="User2 masterjava03" email="user2m03@usermail.ru" city="mnsk" flag="DELETED"/>
        </Group>
    </Project>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
</Payload>
